  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      autovacuum_analyze_scale_factor: "0.01"
      autovacuum_max_workers: "4"
      autovacuum_naptime: 2s
      autovacuum_vacuum_cost_delay: 5ms
      autovacuum_vacuum_cost_limit: "300"
      autovacuum_vacuum_scale_factor: "0.02"
      bgwriter_delay: 10ms
      bgwriter_lru_maxpages: "1000"
      bgwriter_lru_multiplier: "5.0"
      checkpoint_completion_target: "0.95"
      checkpoint_timeout: 15min
      dynamic_shared_memory_type: posix
      effective_cache_size: 24GB
      effective_io_concurrency: "200"
      full_page_writes: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_min_duration_statement: "5000"
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      maintenance_work_mem: 1GB
      max_connections: "100"
      max_parallel_workers: "4"
      max_parallel_workers_per_gather: "2"
      max_replication_slots: "32"
      max_wal_size: 32GB
      max_worker_processes: "8"
      min_wal_size: 1GB
      shared_buffers: 20GB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      synchronous_commit: "on"
      track_io_timing: "on"
      wal_buffers: 16MB
      wal_compression: "on"
      wal_keep_size: 512MB
      wal_level: replica
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
      wal_writer_delay: 200ms
      work_mem: 4MB
